[package]
name = "playage"
version = "0.1.0"
authors = ["Renée Kooi <renee@kooi.me>"]
edition = "2018"

[dependencies]
dprun = { path = "crates/dprun" }
rand = "^0.5.0"
tokio = "^0.1.0"

[workspace]
members = [
  "crates/dprun"
]
