[package]
name = "aoc-userpatch"
version = "0.1.0"
authors = ["Renée Kooi <renee@kooi.me>"]
edition = "2018"

[dependencies]
lazy_static = "^1.3.0"

[build-dependencies]
encoding_rs = "^0.8.17"
lde = "^0.3.0"
