[package]
name = "dprun2"
version = "0.1.0"
authors = ["Renée Kooi <renee@kooi.me>"]
edition = "2018"

[dependencies]
async-process = "0.1.2"
async-std = { version = "1.6", default-features = false, features = ["unstable"] }
lazy_static = "1.4"
uuid = { version = "0.8", default-features = false }
